# Generated by Django 5.1.3 on 2024-12-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('appointment_number', models.IntegerField()),
                ('reports', models.FileField(upload_to='patient_files')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
