# Generated by Django 5.1.3 on 2024-12-05 13:35

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=20)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('emergency_contact', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=200)),
                ('time', models.TimeField()),
            ],
        ),
    ]
