# Generated by Django 5.1.3 on 2024-12-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='department',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Dermatology', 'Dermatology'), ('ENT', 'ENT'), ('Gastroenterology', 'Gastroenterology')], max_length=200),
        ),
    ]
