# Generated by Django 5.1.3 on 2024-12-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_bookappointment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='hospital',
            field=models.CharField(default='no hospital', max_length=400),
        ),
    ]
